import { describe, it, expect } from 'vitest'
import {
  boilerplateKeys,
  contentToText,
  meaningfulUserText,
  previewKey,
  previewRestatesTitle,
  stripCommandBlocks,
  stripReminders
} from './transcript-text'

describe('stripCommandBlocks', () => {
  it('removes a paired command block with its content', () => {
    expect(
      stripCommandBlocks('<command-message>commit</command-message><command-name>commit</command-name>')
    ).toBe('')
  })

  it('removes variants it has never seen', () => {
    // Matched by shape, not by a list. The CLI adds tags without asking, and a list
    // would need editing every time one appears.
    expect(stripCommandBlocks('<command-args>--amend</command-args>keep')).toBe('keep')
    expect(stripCommandBlocks('<local-command-stdout>noise</local-command-stdout>keep')).toBe('keep')
    expect(stripCommandBlocks('<local-command-something-new>x</local-command-something-new>keep')).toBe(
      'keep'
    )
  })

  it('removes an unpaired tag left by a truncated write', () => {
    expect(stripCommandBlocks('<local-command-caveat>Caveat: The messages below')).toBe(
      'Caveat: The messages below'
    )
  })

  it('leaves ordinary angle brackets alone', () => {
    expect(stripCommandBlocks('if (a < b) return <div>')).toBe('if (a < b) return <div>')
  })

  it('keeps the prose that surrounds a block', () => {
    expect(stripCommandBlocks('before<command-name>x</command-name>after')).toBe('beforeafter')
  })
})

describe('stripReminders', () => {
  it('removes a system-reminder block', () => {
    expect(stripReminders('real text<system-reminder>injected</system-reminder>')).toBe('real text')
  })
})

describe('contentToText', () => {
  it('takes a plain string', () => {
    expect(contentToText('hello')).toBe('hello')
  })

  it('joins the text blocks of an array', () => {
    expect(
      contentToText([{ type: 'text', text: 'one' }, { type: 'tool_use' }, { type: 'text', text: 'two' }])
    ).toBe('one two')
  })

  it('is empty for anything else', () => {
    expect(contentToText(undefined)).toBe('')
    expect(contentToText(42)).toBe('')
    expect(contentToText([{ type: 'tool_use' }])).toBe('')
  })
})

describe('meaningfulUserText', () => {
  it('is empty for an entry that is only a slash command', () => {
    // Empty is the signal that lets the caller fall through to the next user entry,
    // which is what makes the preview the conversation instead of the plumbing.
    expect(meaningfulUserText('<command-message>commit</command-message><command-name>commit</command-name>')).toBe('')
  })

  it('drops a leading slash-command line and keeps what followed', () => {
    expect(meaningfulUserText('/security-review\ncheck the auth middleware too')).toBe(
      'check the auth middleware too'
    )
  })

  it('keeps a slash that is not a leading command', () => {
    expect(meaningfulUserText('use src/main/index.ts')).toBe('use src/main/index.ts')
    expect(meaningfulUserText('what about 3 / 4 of the rows?')).toBe('what about 3 / 4 of the rows?')
  })

  it('recovers the prose hidden under a caveat wrapper', () => {
    // The real shape from the measured project: 14 of 52 sessions showed this raw.
    const raw =
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>\nRemove the automatic context name from task creation'
    expect(meaningfulUserText(raw)).toBe('Remove the automatic context name from task creation')
  })

  it('collapses whitespace so previews are one line', () => {
    expect(meaningfulUserText('a\n\n  b\tc')).toBe('a b c')
  })
})

describe('previewRestatesTitle', () => {
  it('is true when they say the same thing', () => {
    expect(previewRestatesTitle('Fix the corners', 'Fix the corners')).toBe(true)
    expect(previewRestatesTitle('fix   the CORNERS', 'Fix the corners')).toBe(true)
  })

  it('ignores punctuation', () => {
    // Real pair from the measured project. The title is generated from the message,
    // so the two differ by a question mark and nothing else.
    expect(previewRestatesTitle('whats left to do?', "What's left to do")).toBe(true)
  })

  it('catches a leading filler word', () => {
    // Also real. A prefix-only comparison missed every one of these.
    expect(
      previewRestatesTitle('lets deploy the unreleased version', 'Deploy the unreleased version')
    ).toBe(true)
    expect(previewRestatesTitle('can you fix the corners', 'Fix the corners')).toBe(true)
  })

  it('keeps a preview that genuinely elaborates', () => {
    // The slack is what draws this line: past a few extra words the preview is
    // saying something the title does not.
    expect(
      previewRestatesTitle(
        'fix this and the percentage should be when pressed on the account not on the chat',
        'Fix account percentage display'
      )
    ).toBe(false)
    expect(
      previewRestatesTitle('Fix the corners — the top-left one clips the badge at 1280px', 'Fix the corners')
    ).toBe(false)
  })

  it('is false when the preview is about something else', () => {
    expect(previewRestatesTitle('the auth middleware drops the header', 'Fix the corners')).toBe(false)
  })

  it('is false when either side is empty', () => {
    expect(previewRestatesTitle('', 'Fix the corners')).toBe(false)
    expect(previewRestatesTitle('Fix the corners', '')).toBe(false)
  })
})

describe('boilerplateKeys', () => {
  const REVIEW =
    'Review this change for security vulnerabilities. Changed files (you may Read these and any other file in the repo): -'

  it('flags an opening shared by three or more sessions', () => {
    const keys = boilerplateKeys([REVIEW, REVIEW, REVIEW, 'something else'])
    expect(keys.has(previewKey(REVIEW))).toBe(true)
    expect(keys.has(previewKey('something else'))).toBe(false)
  })

  it('leaves two alone — that is a coincidence, not a template', () => {
    expect(boilerplateKeys([REVIEW, REVIEW]).size).toBe(0)
  })

  it('matches openings that diverge later', () => {
    // Two runs of the same command differ after the boilerplate (different file
    // lists), so comparing whole previews would find no duplicates at all.
    const keys = boilerplateKeys([
      REVIEW + ' app/models/user.rb',
      REVIEW + ' config/routes.rb',
      REVIEW + ' Gemfile.lock'
    ])
    expect(keys.size).toBe(1)
  })

  it('ignores empty previews', () => {
    expect(boilerplateKeys(['', '', '', '']).size).toBe(0)
  })

  it('is scoped to what it is given', () => {
    // The caller passes one project's previews: /security-review is noise where it
    // runs weekly and a fine preview where it ran once.
    expect(boilerplateKeys([REVIEW]).size).toBe(0)
  })
})
